---
title: "p8105_hw5_lr3257"
author: "Leonor Rui"
date: "2024-11-10"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

```{r}
bday_sim = function(n){
  bdays = sample(1:365, size = n, replace = TRUE)
  
  duplicate = length(unique(bdays)) < n 
  
  return(duplicate)
}
```

```{r}
prob_shared = c()

for (n in 2:50){
  
  num_shared = 0
  
  for (i in 1:10000){
    
    if (bday_sim(n) == TRUE){
      
      num_shared = num_shared + 1
      
    }
  }
  prob_shared = c(prob_shared, num_shared/10000)
}
```

```{r, warning=FALSE}
samp_size = 2:50
bday_df = data.frame(samp_size, prob_shared)

bday_df |>
  ggplot(aes(x = samp_size, y = prob_shared)) +
  geom_point() + 
  geom_smooth(size = 0.5) +
  labs(
    title = "Scatterplot of Group Size versus Probability of Shared Birthdays",
    x = "Group Size", 
    y = "Prob Shared Birthday"
  )
```

As the graph shows, the probability of having at least two people sharing the same birthday increases sharply as the group size increases at first until it hits 50%. After this, the growth slows down as it approaches 100% but does not fully reach it. 












